-- SmartSwing AI — Match Analysis / Phase A — PR 5 slice B1
--
-- Adds match-report persistence columns to `analysis_reports`. We stay on
-- the same table (rather than spinning a new `match_reports`) so the
-- existing dashboard "recent reports" list surfaces both single-swing and
-- match reports with one query — the UI branches on `is_match_report`.
--
-- Design:
--  - `is_match_report`        : fast filter for dashboard tabs.
--  - `match_rallies`          : jsonb array of per-rally entries from
--                               aggregateMatch().rallies. The drill-down
--                               poses are stripped before persistence
--                               (only included in the in-memory drill-down
--                               payload for the paid UI; saved reports
--                               store only summary metrics per rally to
--                               keep row size bounded — a 30-min match
--                               with ~80 rallies keeps the row <50 KB).
--  - `match_summary`          : jsonb with rallyCount, shotBreakdown,
--                               longestRallyFrames, avgRallyDurationSeconds,
--                               spanSeconds — ready for the summary cards
--                               without re-aggregation.
--  - `subject_track_id`       : the track the user picked; useful for
--                               debugging + future "re-pick" re-runs.

ALTER TABLE IF EXISTS public.analysis_reports
  ADD COLUMN IF NOT EXISTS is_match_report    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS match_rallies      jsonb   NULL,
  ADD COLUMN IF NOT EXISTS match_summary      jsonb   NULL,
  ADD COLUMN IF NOT EXISTS subject_track_id   text    NULL;

-- Dashboard filter support — only index rows actually flagged as match
-- reports so the index stays cheap (partial index).
CREATE INDEX IF NOT EXISTS analysis_reports_match_reports_idx
  ON public.analysis_reports (user_id, created_at DESC)
  WHERE is_match_report = true;

COMMENT ON COLUMN public.analysis_reports.is_match_report IS
  'True when this row was generated by match-mode (per-rally report). False for single-swing reports.';

COMMENT ON COLUMN public.analysis_reports.match_rallies IS
  'JSON array of per-rally entries: [{id, peakFrame, startFrame, endFrame, shotType, durationSeconds, peakTime}]. Drill-down pose windows are NOT stored here — they live only in the in-memory payload for the paid UI.';

COMMENT ON COLUMN public.analysis_reports.match_summary IS
  'Aggregate match stats: {rallyCount, shotBreakdown, shotBreakdownPct, longestRallyFrames, avgRallyDurationSeconds, spanSeconds}.';

COMMENT ON COLUMN public.analysis_reports.subject_track_id IS
  'The tracker-assigned id of the player the user picked (e.g. "track-2"). Useful for debugging + future "re-pick" re-runs without redoing detection.';
